$p = "C:\Users\Usuario\.gemini\antigravity\playground\polar-newton\franquias-inspirar"
$html = [System.Text.StringBuilder]::new()

[void]$html.AppendLine('<!DOCTYPE html>')
[void]$html.AppendLine('<html lang="pt-BR">')
[void]$html.AppendLine('<head>')
[void]$html.AppendLine('<meta charset="UTF-8" /><meta name="viewport" content="width=device-width,initial-scale=1.0" />')
[void]$html.AppendLine('<title>Seja um Franqueado | Faculdade Inspirar</title>')
[void]$html.AppendLine('<meta name="description" content="Abra sua unidade da Faculdade Inspirar - maior rede de franquias de pos-graduacao em Saude do Brasil. 28+ anos, 100mil alunos formados." />')
[void]$html.AppendLine('<link rel="preconnect" href="https://fonts.googleapis.com" />')
[void]$html.AppendLine('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />')
[void]$html.AppendLine('<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />')
[void]$html.AppendLine('<link rel="stylesheet" href="styles.css" />')
[void]$html.AppendLine('</head><body>')

# NAVBAR
[void]$html.AppendLine('<nav class="navbar" id="navbar"><div class="nav-container">')
[void]$html.AppendLine('<a href="#hero" class="nav-logo"><img src="logo.png" alt="Faculdade Inspirar" class="nav-logo-img" /><div class="nav-logo-text"><span class="logo-faculdade">FACULDADE</span><span class="logo-inspirar">INSPIRAR</span></div></a>')
[void]$html.AppendLine('<ul class="nav-links" id="nav-links"><li><a href="#sobre" id="nav-sobre">Sobre</a></li><li><a href="#diferenciais" id="nav-diferenciais">Diferenciais</a></li><li><a href="#investimento" id="nav-investimento">Investimento</a></li><li><a href="#depoimentos" id="nav-depoimentos">Depoimentos</a></li><li><a href="#faq" id="nav-faq">FAQ</a></li></ul>')
[void]$html.AppendLine('<div class="nav-actions"><a href="#contato" class="btn btn-primary btn-nav" id="btn-nav-franqueado">Quero ser Franqueado</a><button class="hamburger" id="hamburger" aria-label="Abrir menu" aria-expanded="false"><span></span><span></span><span></span></button></div>')
[void]$html.AppendLine('</div></nav>')

# HERO
[void]$html.AppendLine('<section class="hero" id="hero"><div class="hero-bg"><img src="hero.png" alt="Campus Faculdade Inspirar" class="hero-img" /><div class="hero-overlay"></div><div class="hero-gradient"></div></div>')
[void]$html.AppendLine('<div class="hero-content container"><div class="hero-tags"><span class="tag tag-blue" id="tag-premiada">&#11088; Premiada por 8 anos consecutivos</span><span class="tag tag-dark" id="tag-franquias">&#127942; Maior rede de pos-graduacao em Saude do Brasil</span></div>')
[void]$html.AppendLine('<h1 class="hero-title">Transforme sua cidade com a<br /><span class="gradient-text">Faculdade Inspirar</span></h1>')
[void]$html.AppendLine('<p class="hero-subtitle">Seja parte da maior rede de franquias de educacao na area da Saude do Brasil.<br />Mais de 28 anos de tradicao, +100 mil alunos formados e presenca em todo o pais.</p>')
[void]$html.AppendLine('<div class="hero-stats"><div class="hero-stat" id="stat-anos"><span class="stat-number">28<span class="stat-plus">+</span></span><span class="stat-label">Anos de mercado</span></div><div class="hero-stat-divider"></div><div class="hero-stat" id="stat-alunos"><span class="stat-number">100K<span class="stat-plus">+</span></span><span class="stat-label">Alunos formados</span></div><div class="hero-stat-divider"></div><div class="hero-stat" id="stat-unidades"><span class="stat-number">40<span class="stat-plus">+</span></span><span class="stat-label">Unidades no Brasil</span></div><div class="hero-stat-divider"></div><div class="hero-stat" id="stat-cursos"><span class="stat-number">1000<span class="stat-plus">+</span></span><span class="stat-label">Cursos disponiveis</span></div></div>')
[void]$html.AppendLine('<div class="hero-ctas"><a href="#contato" class="btn btn-primary btn-lg" id="btn-hero-quero">Quero ser Franqueado</a><a href="#sobre" class="btn btn-outline btn-lg" id="btn-hero-saibamais">Saiba mais &#8595;</a></div>')
[void]$html.AppendLine('</div><div class="hero-scroll-indicator" aria-hidden="true"><div class="scroll-dot"></div></div></section>')

# LOGO WALL
[void]$html.AppendLine('<section class="logo-wall" id="logo-wall"><div class="container"><p class="logo-wall-label">Reconhecida pelas maiores organizacoes do mercado</p><div class="logo-wall-track">')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-serasa"><div class="award-icon">&#127885;</div><span>Serasa Experian</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-pegn"><div class="award-icon">&#128240;</div><span>Peq. Empresas &amp; Grandes Neg.</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-8anos"><div class="award-icon">&#11088;</div><span>8 anos consecutivos no Top 5</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-brasil"><div class="award-icon">&#127464;&#127479;</div><span>Todo o Brasil</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-europa"><div class="award-icon">&#127758;</div><span>Portugal &amp; Holanda</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-mec"><div class="award-icon">&#128203;</div><span>Autorizada pelo MEC</span></div>')
[void]$html.AppendLine('</div></div></section>')

# SOBRE
[void]$html.AppendLine('<section class="sobre" id="sobre"><div class="container"><div class="sobre-grid"><div class="sobre-content">')
[void]$html.AppendLine('<span class="section-eyebrow">Nossa Historia</span><h2 class="section-title">A maior e melhor rede de franquias de pos-graduacao do Brasil</h2>')
[void]$html.AppendLine('<p class="sobre-text">Ha mais de duas decadas no mercado, o Grupo Inspirar esta presente em todas as regioes do pais, alem de sedes em Portugal e na Holanda. Destaca-se como instituicao referencia de ensino na area da Saude, com cursos de Graduacao, Pos-graduacao, Extensao e programas de Mestrado e Doutorado.</p>')
[void]$html.AppendLine('<p class="sobre-text">Reconhecida como a maior e melhor rede de franquias de pos-graduacao do Brasil segundo a Serasa Experian e a Revista Pequenas Empresas &amp; Grandes Negocios.</p>')
[void]$html.AppendLine('<div class="sobre-badges"><span class="badge" id="badge-saude">&#129658; Referencia em Saude</span><span class="badge" id="badge-ead">&#128187; EAD + Presencial</span><span class="badge" id="badge-pos">&#127891; Pos-Graduacao</span><span class="badge" id="badge-extensao">&#128218; Extensao</span><span class="badge" id="badge-mestrado">&#128300; Mestrado e Doutorado</span></div>')
[void]$html.AppendLine('</div><div class="sobre-visual"><div class="sobre-img-wrapper"><img src="franchisee.png" alt="Franqueado de sucesso da Faculdade Inspirar" class="sobre-img" /><div class="sobre-img-card" id="sobre-card-retorno"><div class="img-card-icon">&#128176;</div><div class="img-card-content"><strong>Retorno em 18-24 meses</strong><span>Prazo estimado de ROI</span></div></div></div></div>')
[void]$html.AppendLine('</div></div></section>')

# BENTO / DIFERENCIAIS
[void]$html.AppendLine('<section class="diferenciais" id="diferenciais"><div class="container">')
[void]$html.AppendLine('<div class="section-header"><span class="section-eyebrow">Por que escolher a Inspirar?</span><h2 class="section-title">Diferenciais que fazem a diferenca</h2><p class="section-subtitle">Tudo que voce precisa para construir um negocio solido e lucrativo.</p></div>')
[void]$html.AppendLine('<div class="bento-grid">')
[void]$html.AppendLine('<div class="bento-card bento-large" id="bento-marca"><div class="bento-icon">&#127942;</div><h3>Marca Premium &amp; Consolidada</h3><p>28+ anos de historia e autoridade reconhecida no mercado de saude. Uma marca que abre portas.</p><div class="bento-illustration"><img src="illustration.png" alt="Ilustracao educacao saude" /></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-tall" id="bento-suporte"><div class="bento-icon">&#129309;</div><h3>Suporte Completo</h3><p>Apoio comercial, academico, juridico e de marketing. Voce nunca estara sozinho.</p><ul class="bento-list"><li>&#10003; Treinamento inicial completo</li><li>&#10003; Suporte academico 24/7</li><li>&#10003; Materiais de marketing</li><li>&#10003; Consultoria de negocios</li></ul></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium" id="bento-cursos"><div class="bento-icon">&#128218;</div><h3>+1.000 Cursos</h3><p>Portfolio vasto cobrindo toda a cadeia de saude, bem-estar, estetica e longevidade.</p><div class="bento-tags"><span class="mini-tag">Fisioterapia</span><span class="mini-tag">Nutricao</span><span class="mini-tag">Estetica</span><span class="mini-tag">Psicologia</span><span class="mini-tag">Enfermagem</span><span class="mini-tag">+ muito mais</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium bento-blue" id="bento-retorno"><div class="bento-icon">&#128200;</div><h3>Retorno Rapido</h3><p>Previsao de retorno do investimento entre 18 e 24 meses com modelo validado.</p><div class="bento-metric"><span class="metric-number">18-24</span><span class="metric-label">meses para ROI</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-wide" id="bento-presenca"><div class="bento-icon">&#127758;</div><h3>Presenca Nacional e Internacional</h3><p>Mais de 40 unidades em todas as regioes do Brasil, Portugal e Holanda.</p><div class="bento-cities"><span>Sao Paulo</span><span>Rio de Janeiro</span><span>Curitiba</span><span>Porto Alegre</span><span>Brasilia</span><span>Salvador</span><span>Fortaleza</span><span>Belo Horizonte</span><span>+32 cidades</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium" id="bento-ead"><div class="bento-icon">&#128187;</div><h3>Plataforma EAD Propria</h3><p>Tecnologia de ponta para educacao online com suporte tecnico dedicado.</p></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium bento-dark" id="bento-premiada"><div class="bento-icon">&#11088;</div><h3>Premiada 8x</h3><p>8 anos consecutivos entre as 5 melhores franquias de cursos do Brasil.</p></div>')
[void]$html.AppendLine('</div></div></section>')

# PLANS
[void]$html.AppendLine('<section class="investimento" id="investimento"><div class="container">')
[void]$html.AppendLine('<div class="section-header"><span class="section-eyebrow">Modelos de Franquia</span><h2 class="section-title">Escolha o modelo ideal para voce</h2><p class="section-subtitle">Opcoes flexiveis para diferentes perfis de empreendedores.</p></div>')
[void]$html.AppendLine('<div class="plans-grid">')
[void]$html.AppendLine('<div class="plan-card" id="plan-polo"><div class="plan-badge">Mais Acessivel</div><div class="plan-icon">&#127919;</div><h3 class="plan-name">Polo EAD</h3><p class="plan-desc">Ideal para comecar com menor investimento inicial, operando com cursos 100% online.</p><div class="plan-invest"><span class="invest-from">A partir de</span><div class="invest-value">R$ 240<span class="invest-k">mil</span></div></div><ul class="plan-features"><li><span class="check-icon">&#10003;</span> Cursos EAD completos</li><li><span class="check-icon">&#10003;</span> Plataforma digital propria</li><li><span class="check-icon">&#10003;</span> Suporte academico</li><li><span class="check-icon">&#10003;</span> Material de marketing</li><li><span class="check-icon">&#10003;</span> Treinamento inicial</li></ul><a href="#contato" class="btn btn-outline btn-full" id="btn-plan-polo">Quero este modelo</a></div>')
[void]$html.AppendLine('<div class="plan-card plan-featured" id="plan-unidade"><div class="plan-badge plan-badge-featured">&#11088; Mais Popular</div><div class="plan-icon">&#127963;</div><h3 class="plan-name">Unidade Presencial</h3><p class="plan-desc">Unidade fisica completa com cursos presenciais, semipresenciais e online.</p><div class="plan-invest"><span class="invest-from">A partir de</span><div class="invest-value">R$ 390<span class="invest-k">mil</span></div></div><ul class="plan-features"><li><span class="check-icon">&#10003;</span> Espaco fisico equipado</li><li><span class="check-icon">&#10003;</span> Cursos presenciais + EAD</li><li><span class="check-icon">&#10003;</span> Suporte completo 360</li><li><span class="check-icon">&#10003;</span> Exclusividade territorial</li><li><span class="check-icon">&#10003;</span> Consultoria de expansao</li><li><span class="check-icon">&#10003;</span> Acesso ao portfolio premium</li></ul><a href="#contato" class="btn btn-primary btn-full" id="btn-plan-unidade">Quero este modelo</a></div>')
[void]$html.AppendLine('<div class="plan-card" id="plan-semipresencial"><div class="plan-badge">Flexivel</div><div class="plan-icon">&#128260;</div><h3 class="plan-name">Semipresencial</h3><p class="plan-desc">O melhor dos dois mundos: combine aulas presenciais com conteudo online.</p><div class="plan-invest"><span class="invest-from">Consulte</span><div class="invest-value" style="font-size:1.8rem;line-height:1.2">Condicoes especiais</div></div><ul class="plan-features"><li><span class="check-icon">&#10003;</span> Modelo hibrido</li><li><span class="check-icon">&#10003;</span> Maior flexibilidade</li><li><span class="check-icon">&#10003;</span> Suporte academico</li><li><span class="check-icon">&#10003;</span> Portfolio diversificado</li><li><span class="check-icon">&#10003;</span> Gestao simplificada</li></ul><a href="#contato" class="btn btn-outline btn-full" id="btn-plan-semi">Quero este modelo</a></div>')
[void]$html.AppendLine('</div></div></section>')

# HOW IT WORKS
[void]$html.AppendLine('<section class="como-funciona" id="como-funciona"><div class="container">')
[void]$html.AppendLine('<div class="section-header section-header-light"><span class="section-eyebrow eyebrow-light">Processo Simples</span><h2 class="section-title title-light">Do interesse a abertura em poucos passos</h2></div>')
[void]$html.AppendLine('<div class="steps-list">')
[void]$html.AppendLine('<div class="step-item" id="step-1"><div class="step-number">01</div><div class="step-content"><h3>Preencha o formulario de interesse</h3><p>Nos informe seus dados e a cidade onde deseja abrir. Nossa equipe entra em contato em ate 24h.</p></div><div class="step-icon">&#128203;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-2"><div class="step-number">02</div><div class="step-content"><h3>Apresentacao do modelo de negocio</h3><p>Conheca em detalhes como funciona a franquia, os numeros e o potencial de retorno da sua regiao.</p></div><div class="step-icon">&#128202;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-3"><div class="step-number">03</div><div class="step-content"><h3>Analise e aprovacao</h3><p>Nossa equipe avalia o perfil e a viabilidade do mercado local para garantir o sucesso da unidade.</p></div><div class="step-icon">&#9989;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-4"><div class="step-number">04</div><div class="step-content"><h3>Assinatura do contrato</h3><p>Formalizamos a parceria e voce passa a fazer parte da rede Inspirar oficialmente.</p></div><div class="step-icon">&#9997;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-5"><div class="step-number">05</div><div class="step-content"><h3>Treinamento e abertura</h3><p>Voce recebe todo o suporte para montar sua unidade e acompanhamento nos primeiros meses.</p></div><div class="step-icon">&#128640;</div></div>')
[void]$html.AppendLine('</div></div></section>')

# TESTIMONIALS
[void]$html.AppendLine('<section class="depoimentos" id="depoimentos"><div class="container">')
[void]$html.AppendLine('<div class="section-header"><span class="section-eyebrow">Depoimentos</span><h2 class="section-title">O que nossos franqueados dizem</h2><p class="section-subtitle">Historias reais de quem escolheu investir no futuro com a Faculdade Inspirar.</p></div>')
[void]$html.AppendLine('<div class="testimonials-grid">')
[void]$html.AppendLine('<div class="testimonial-card testimonial-featured" id="testimonial-1"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Abri minha unidade em Curitiba ha 4 anos e desde o primeiro semestre ja estava recuperando meu investimento. O suporte da Inspirar e impressionante nunca me senti sozinha nessa jornada. A marca ja vem com credibilidade, o que facilita muito a captacao de alunos.</p><div class="testimonial-author"><img src="avatar1.png" alt="Mariana Costa" class="avatar" /><div class="author-info"><strong id="testimonial-author-1">Mariana Costa</strong><span>Franqueada - Curitiba, PR</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('<div class="testimonial-card" id="testimonial-2"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Estava buscando um negocio solido na area da educacao e a Inspirar foi a escolha certa. Portfolio imenso de cursos na area da saude e uma demanda crescente. Em 22 meses ja tinha recuperado tudo que investi.</p><div class="testimonial-author"><img src="avatar2.png" alt="Ricardo Almeida" class="avatar" /><div class="author-info"><strong id="testimonial-author-2">Ricardo Almeida</strong><span>Franqueado - Porto Alegre, RS</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('<div class="testimonial-card" id="testimonial-3"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Como profissional da saude, escolhi a Inspirar porque acredito no impacto da educacao de qualidade. O modelo de franquia e muito bem estruturado e o retorno superou minhas expectativas.</p><div class="testimonial-author"><img src="avatar3.png" alt="Camila Santos" class="avatar" /><div class="author-info"><strong id="testimonial-author-3">Camila Santos</strong><span>Franqueada - Sao Paulo, SP</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('</div></div></section>')

# FAQ
[void]$html.AppendLine('<section class="faq" id="faq"><div class="container"><div class="faq-layout">')
[void]$html.AppendLine('<div class="faq-header-col"><span class="section-eyebrow">FAQ</span><h2 class="section-title">Perguntas frequentes</h2><p class="faq-desc">Tire suas principais duvidas sobre o modelo de franquia da Faculdade Inspirar.</p><a href="#contato" class="btn btn-primary" id="btn-faq-contato">Falar com um consultor</a></div>')
[void]$html.AppendLine('<div class="faq-list" id="faq-list">')
[void]$html.AppendLine('<div class="accordion-item" id="faq-1"><button class="accordion-trigger" id="faq-trigger-1" aria-expanded="false" aria-controls="faq-content-1"><span>Qual o investimento inicial para abrir uma franquia?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-1"><p>O investimento varia conforme o modelo. Para um polo EAD comeca a partir de R$ 240 mil. Para uma unidade presencial completa, chega a R$ 390 mil. Nossa equipe pode detalhar os valores com base no seu perfil e cidade.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-2"><button class="accordion-trigger" id="faq-trigger-2" aria-expanded="false" aria-controls="faq-content-2"><span>Em quanto tempo posso recuperar meu investimento?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-2"><p>O prazo estimado de retorno (ROI) e de 18 a 24 meses, dependendo do modelo e da performance da unidade. Esse prazo e baseado na media historica das unidades da rede.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-3"><button class="accordion-trigger" id="faq-trigger-3" aria-expanded="false" aria-controls="faq-content-3"><span>Preciso ter experiencia no setor de educacao?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-3"><p>Nao e necessario. A Faculdade Inspirar oferece treinamento inicial completo cobrindo todas as areas: academico, comercial, financeiro e operacional.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-4"><button class="accordion-trigger" id="faq-trigger-4" aria-expanded="false" aria-controls="faq-content-4"><span>Como funciona o suporte da franqueadora?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-4"><p>O suporte e completo e multidisciplinar: academico, comercial, marketing com materiais e campanhas nacionais, juridico, financeiro e consultoria continua de negocios.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-5"><button class="accordion-trigger" id="faq-trigger-5" aria-expanded="false" aria-controls="faq-content-5"><span>Posso abrir uma unidade em qualquer cidade do Brasil?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-5"><p>Sim! A Faculdade Inspirar esta em expansao em todo o Brasil. Analisamos a viabilidade de mercado de cada cidade e concedemos territorios exclusivos.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-6"><button class="accordion-trigger" id="faq-trigger-6" aria-expanded="false" aria-controls="faq-content-6"><span>Quais cursos posso oferecer na minha unidade?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-6"><p>Mais de 1.000 cursos nas areas de Saude, Bem-estar, Longevidade e Beleza, incluindo pos-graduacao, MBA, extensao, graduacao e formacao. Nas modalidades presencial, semipresencial e EAD.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-7"><button class="accordion-trigger" id="faq-trigger-7" aria-expanded="false" aria-controls="faq-content-7"><span>A Faculdade Inspirar e credenciada pelo MEC?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-7"><p>Sim, a Faculdade Inspirar e devidamente credenciada e autorizada pelo MEC. Todos os diplomas tem validade nacional.</p></div></div>')
[void]$html.AppendLine('</div></div></div></section>')

# CONTACT
[void]$html.AppendLine('<section class="contato" id="contato"><div class="contato-bg"></div><div class="container"><div class="contato-layout">')
[void]$html.AppendLine('<div class="contato-info"><span class="section-eyebrow eyebrow-light">De o primeiro passo</span><h2 class="section-title title-light">Pronto para transformar sua cidade?</h2><p class="contato-desc">Preencha o formulario e nossa equipe entrara em contato em ate 24 horas com uma proposta personalizada.</p>')
[void]$html.AppendLine('<div class="contato-features"><div class="contato-feature" id="cf-1"><div class="cf-icon">&#9889;</div><div><strong>Resposta em 24h</strong><span>Nossa equipe e agil e comprometida</span></div></div><div class="contato-feature" id="cf-2"><div class="cf-icon">&#128274;</div><div><strong>Dados protegidos</strong><span>Suas informacoes estao seguras</span></div></div><div class="contato-feature" id="cf-3"><div class="cf-icon">&#127919;</div><div><strong>Proposta personalizada</strong><span>Analise para seu mercado</span></div></div></div>')
[void]$html.AppendLine('<div class="contato-whatsapp"><a href="https://wa.me/5508006022828" class="btn btn-whatsapp" id="btn-whatsapp" target="_blank" rel="noopener noreferrer"><svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg>Chamar no WhatsApp</a></div></div>')
[void]$html.AppendLine('<div class="contato-form-wrapper"><form class="contato-form" id="contato-form" novalidate><h3 class="form-title">Quero ser Franqueado</h3>')
[void]$html.AppendLine('<div class="form-group"><label for="input-nome">Nome completo *</label><input type="text" id="input-nome" name="nome" placeholder="Seu nome completo" required /></div>')
[void]$html.AppendLine('<div class="form-row"><div class="form-group"><label for="input-email">E-mail *</label><input type="email" id="input-email" name="email" placeholder="seu@email.com" required /></div><div class="form-group"><label for="input-telefone">WhatsApp *</label><input type="tel" id="input-telefone" name="telefone" placeholder="(00) 00000-0000" required /></div></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-cidade">Cidade de interesse *</label><input type="text" id="input-cidade" name="cidade" placeholder="Cidade onde deseja abrir a unidade" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-modelo">Modelo de franquia</label><select id="input-modelo" name="modelo"><option value="">Selecione um modelo</option><option value="polo-ead">Polo EAD</option><option value="unidade-presencial">Unidade Presencial</option><option value="semipresencial">Semipresencial</option><option value="nao-sei">Ainda nao sei, quero orientacao</option></select></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-mensagem">Mensagem (opcional)</label><textarea id="input-mensagem" name="mensagem" rows="3" placeholder="Conte-nos um pouco mais sobre voce..."></textarea></div>')
[void]$html.AppendLine('<div class="form-check"><input type="checkbox" id="input-termos" name="termos" required /><label for="input-termos">Concordo com a <a href="https://www.inspirar.com.br/politica-de-privacidade/" target="_blank" rel="noopener noreferrer">Politica de Privacidade</a> e autorizo o contato comercial.</label></div>')
[void]$html.AppendLine('<button type="submit" class="btn btn-primary btn-full btn-lg" id="btn-submit-form">Enviar meu interesse <span class="btn-arrow">&#8594;</span></button>')
[void]$html.AppendLine('<p class="form-disclaimer">&#128274; Seus dados estao protegidos. Nao fazemos spam.</p>')
[void]$html.AppendLine('</form></div></div></div></section>')

# FOOTER
[void]$html.AppendLine('<footer class="footer"><div class="container"><div class="footer-top">')
[void]$html.AppendLine('<div class="footer-brand"><div class="footer-logo"><img src="logo.png" alt="Faculdade Inspirar" class="footer-logo-img" /><div class="nav-logo-text"><span class="logo-faculdade">FACULDADE</span><span class="logo-inspirar">INSPIRAR</span></div></div><p class="footer-tagline">Inspirar e encantar faz parte do nosso dia a dia.</p><div class="footer-social"><a href="https://www.inspirar.com.br" class="social-link" id="social-site" target="_blank" rel="noopener noreferrer" title="Site">&#127760;</a><a href="https://wa.me/5508006022828" class="social-link" id="social-whatsapp" target="_blank" rel="noopener noreferrer" title="WhatsApp">&#128172;</a></div></div>')
[void]$html.AppendLine('<div class="footer-links"><div class="footer-col"><h4>Institucional</h4><ul><li><a href="https://www.inspirar.com.br/sobre" target="_blank">Sobre a Inspirar</a></li><li><a href="https://www.inspirar.com.br" target="_blank">Unidades</a></li><li><a href="https://www.inspirar.com.br/trabalhe-conosco" target="_blank">Trabalhe Conosco</a></li><li><a href="https://www.inspirar.com.br/ouvidoria" target="_blank">Ouvidoria</a></li></ul></div><div class="footer-col"><h4>Cursos</h4><ul><li><a href="https://www.inspirar.com.br" target="_blank">Pos-Graduacao</a></li><li><a href="https://www.inspirar.com.br/home-graduacao/" target="_blank">Graduacao</a></li><li><a href="https://www.inspirar.com.br" target="_blank">Extensao</a></li><li><a href="https://www.inspirar.com.br/brasil/" target="_blank">EAD</a></li></ul></div><div class="footer-col"><h4>Franquia</h4><ul><li><a href="#diferenciais">Diferenciais</a></li><li><a href="#investimento">Modelos</a></li><li><a href="#depoimentos">Depoimentos</a></li><li><a href="#contato">Seja Franqueado</a></li></ul></div></div>')
[void]$html.AppendLine('</div><div class="footer-bottom"><p>&copy; 2026 Faculdade Inspirar. Todos os direitos reservados.</p><a href="https://www.inspirar.com.br/politica-de-privacidade/" target="_blank" rel="noopener noreferrer" class="footer-privacy">Politica de Privacidade</a></div></div></footer>')

# FLOATING + MODAL + SCRIPT
[void]$html.AppendLine('<div class="floating-cta" id="floating-cta"><a href="#contato" class="btn btn-primary" id="btn-floating">&#128188; Quero ser Franqueado</a></div>')
[void]$html.AppendLine('<div class="modal-overlay" id="modal-overlay" style="display:none"><div class="modal-box"><div class="modal-icon">&#127881;</div><h3 id="modal-title">Interesse registrado!</h3><p>Nossa equipe entrara em contato em ate 24 horas com uma proposta personalizada.</p><button class="btn btn-primary" id="modal-close">Fechar</button></div></div>')
[void]$html.AppendLine('<script src="script.js"></script></body></html>')

[System.IO.File]::WriteAllText("$p\index.html", $html.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "HTML written: $([System.IO.File]::ReadAllBytes("$p\index.html").Length) bytes"
