$p = "C:\Users\Usuario\.gemini\antigravity\playground\polar-newton\franquias-inspirar"
$html = [System.Text.StringBuilder]::new()

[void]$html.AppendLine('<!DOCTYPE html><html lang="pt-BR"><head>')
[void]$html.AppendLine('<meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />')
[void]$html.AppendLine('<title>Seja um Franqueado | Faculdade Inspirar</title>')
[void]$html.AppendLine('<meta name="description" content="Abra sua franquia Faculdade Inspirar - maior rede de pos-graduacao em Saude do Brasil. 29+ anos, 100 mil alunos formados." />')
[void]$html.AppendLine('<link rel="stylesheet" href="styles.css" /></head><body>')

# STICKY TOP BAR
[void]$html.AppendLine('<div class="topbar" id="topbar"><div class="topbar-inner"><img src="Logo branca - horizontal.png" alt="Faculdade Inspirar" class="topbar-logo" /><a href="#contato" class="btn btn-primary btn-sm" id="btn-topbar">Quero ser Franqueado</a></div></div>')

# HERO - fullscreen, sem navbar, sem form aqui
[void]$html.AppendLine('<section class="hero" id="hero"><div class="hero-bg"><img src="hero atualizada.png" alt="Campus Faculdade Inspirar" class="hero-img" /><div class="hero-overlay"></div></div>')
[void]$html.AppendLine('<div class="hero-content"><div class="hero-tags"><span class="tag tag-blue">&#11088; Premiada 8x consecutivos</span><span class="tag tag-dark">&#127942; Maior rede de P&oacute;s em Sa&uacute;de do Brasil</span></div>')
[void]$html.AppendLine('<h1 class="hero-title">Transforme sua cidade com a<br /><span class="gradient-text">Faculdade Inspirar</span></h1>')
[void]$html.AppendLine('<p class="hero-subtitle">A maior rede de franquias de educa&ccedil;&atilde;o na &aacute;rea da Sa&uacute;de do Brasil. 29+ anos de tradi&ccedil;&atilde;o e +100 mil alunos formados.</p>')
[void]$html.AppendLine('<div class="hero-stats"><div class="hero-stat"><span class="stat-number">29<span class="stat-plus">+</span></span><span class="stat-label">Anos de mercado</span></div><div class="hero-stat-divider"></div><div class="hero-stat"><span class="stat-number">100K<span class="stat-plus">+</span></span><span class="stat-label">Alunos formados</span></div><div class="hero-stat-divider"></div><div class="hero-stat"><span class="stat-number">40<span class="stat-plus">+</span></span><span class="stat-label">Unidades</span></div><div class="hero-stat-divider"></div><div class="hero-stat"><span class="stat-number">1000<span class="stat-plus">+</span></span><span class="stat-label">Cursos</span></div></div>')
[void]$html.AppendLine('<a href="#sobre" class="btn btn-primary btn-lg hero-cta" id="btn-hero">Conhe&ccedil;a a franquia &#8595;</a>')
[void]$html.AppendLine('</div><div class="hero-scroll-indicator"><div class="scroll-dot"></div></div></section>')

# SECAO SOBRE - 2 colunas: foto esq | texto dir (Kopenhagen style)
[void]$html.AppendLine('<section class="kop-section kop-about" id="sobre"><div class="kop-row"><div class="kop-col-img"><img src="IMG_7433.JPG" alt="Faculdade Inspirar" class="kop-side-img" /></div><div class="kop-col-text"><span class="section-eyebrow">Nossa Hist&oacute;ria</span><h2 class="section-title">H&aacute; 29 anos inspirando e<br/>transformando vidas</h2><p class="kop-text">O Grupo Inspirar &eacute; presença em todas as regi&otilde;es do Brasil, com sedes tamb&eacute;m em Portugal e na Holanda. Destaca-se como institui&ccedil;&atilde;o refer&ecirc;ncia de ensino na &aacute;rea da Sa&uacute;de.</p><p class="kop-text">Reconhecida como a maior e melhor rede de franquias de p&oacute;s-gradua&ccedil;&atilde;o do Brasil pela Serasa Experian e pela Revista Pequenas Empresas &amp; Grandes Neg&oacute;cios — 8 anos seguidos.</p><div class="kop-badges"><span class="badge">&#129658; Sa&uacute;de</span><span class="badge">&#127891; P&oacute;s-Gradua&ccedil;&atilde;o</span><span class="badge">&#128218; Extens&atilde;o</span><span class="badge">&#128300; Mestrado e Doutorado</span></div><a href="#contato" class="btn btn-primary" id="btn-sobre">Quero ser Franqueado</a></div></div></section>')

# STATS BAR - fundo preto com numeros (Kopenhagen style strip)
[void]$html.AppendLine('<section class="stats-bar"><div class="stats-bar-inner"><div class="stat-item"><span class="sbi-number">29<span class="sbi-plus">+</span></span><span class="sbi-label">Anos de mercado</span></div><div class="stat-bar-div"></div><div class="stat-item"><span class="sbi-number">100K<span class="sbi-plus">+</span></span><span class="sbi-label">Alunos formados</span></div><div class="stat-bar-div"></div><div class="stat-item"><span class="sbi-number">40<span class="sbi-plus">+</span></span><span class="sbi-label">Unidades no Brasil</span></div><div class="stat-bar-div"></div><div class="stat-item"><span class="sbi-number">1000<span class="sbi-plus">+</span></span><span class="sbi-label">Cursos dispon&iacute;veis</span></div><div class="stat-bar-div"></div><div class="stat-item"><span class="sbi-number">18<span class="sbi-unit">-24m</span></span><span class="sbi-label">Prazo de retorno</span></div></div></section>')

# DIFERENCIAIS - BENTO GRID
[void]$html.AppendLine('<section class="diferenciais" id="diferenciais"><div class="container"><div class="section-header"><span class="section-eyebrow">Por que escolher a Inspirar?</span><h2 class="section-title">Diferenciais que fazem a diferen&ccedil;a</h2><p class="section-subtitle">Tudo que voc&ecirc; precisa para construir um neg&oacute;cio s&oacute;lido e lucrativo na &aacute;rea da sa&uacute;de.</p></div>')
[void]$html.AppendLine('<div class="bento-grid">')
[void]$html.AppendLine('<div class="bento-card bento-large"><div class="bento-icon">&#127942;</div><h3>Marca Premium &amp; Consolidada</h3><p>29+ anos de hist&oacute;ria e autoridade reconhecida no mercado de sa&uacute;de. Uma marca que abre portas e gera confian&ccedil;a instant&acirc;nea.</p></div>')
[void]$html.AppendLine('<div class="bento-card bento-tall"><div class="bento-icon">&#129309;</div><h3>Suporte Completo</h3><p>Apoio comercial, acad&ecirc;mico, jur&iacute;dico e de marketing. Voc&ecirc; nunca estar&aacute; sozinho.</p><ul class="bento-list"><li>&#10003; Treinamento inicial</li><li>&#10003; Suporte acad&ecirc;mico 24/7</li><li>&#10003; Materiais de marketing</li><li>&#10003; Consultoria de neg&oacute;cios</li></ul></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium"><div class="bento-icon">&#128218;</div><h3>+1.000 Cursos</h3><p>Sa&uacute;de, bem-estar, est&eacute;tica e longevidade.</p><div class="bento-tags"><span class="mini-tag">Fisioterapia</span><span class="mini-tag">Est&eacute;tica</span><span class="mini-tag">Psicologia</span><span class="mini-tag">Enfermagem</span><span class="mini-tag">Osteopatia</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium bento-blue"><div class="bento-icon">&#128200;</div><h3>Retorno R&aacute;pido</h3><p>Previs&atilde;o de retorno entre 18 e 24 meses com modelo validado.</p><div class="bento-metric"><span class="metric-number">18&ndash;24</span><span class="metric-label">meses para ROI</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-wide"><div class="bento-icon">&#127758;</div><h3>Presen&ccedil;a Nacional</h3><p>Mais de 40 unidades em todas as regi&otilde;es do Brasil, Portugal e Holanda.</p><div class="bento-cities"><span>S&atilde;o Paulo</span><span>Rio de Janeiro</span><span>Curitiba</span><span>Porto Alegre</span><span>Bras&iacute;lia</span><span>Salvador</span><span>Fortaleza</span><span>+ 34 cidades</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium bento-card-dark"><div class="bento-icon" style="color:#FFD700">&#11088;</div><h3>Premiada 8x</h3><p>8 anos consecutivos entre as 5 melhores franquias de cursos do Brasil.</p></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium"><div class="bento-icon">&#127968;</div><h3>Exclusividade Territorial</h3><p>Cada franqueado recebe exclusividade na sua cidade, garantindo prote&ccedil;&atilde;o de mercado.</p></div>')
[void]$html.AppendLine('</div></div></section>')

# SECAO SUPORTE - fundo azul + foto lado a lado invertido (Kopenhagen style)
[void]$html.AppendLine('<section class="kop-section kop-support"><div class="kop-row kop-row-reverse"><div class="kop-col-text"><span class="section-eyebrow eyebrow-light">Suporte Total</span><h2 class="section-title title-light">Voc&ecirc; nunca empreende sozinho</h2><p class="kop-text kop-text-light">Desde o primeiro dia, nossa equipe estar&aacute; ao seu lado com suporte completo em todas as &aacute;reas do neg&oacute;cio.</p><ul class="kop-checklist"><li><span class="kop-check">&#10003;</span> Consultoria de implanta&ccedil;&atilde;o</li><li><span class="kop-check">&#10003;</span> Treinamento acad&ecirc;mico e comercial</li><li><span class="kop-check">&#10003;</span> Marketing nacional e materiais de venda</li><li><span class="kop-check">&#10003;</span> Suporte jur&iacute;dico e financeiro</li><li><span class="kop-check">&#10003;</span> Plataforma de gest&atilde;o exclusiva</li></ul><a href="#contato" class="btn btn-white" id="btn-support">Quero ser Franqueado</a></div><div class="kop-col-img"><img src="franchisee.png" alt="Franqueado Inspirar de sucesso" class="kop-side-img" /></div></div></section>')

# PASSO A PASSO - horizontal (Kopenhagen style)
[void]$html.AppendLine('<section class="como-funciona" id="como-funciona"><div class="container"><div class="section-header"><span class="section-eyebrow">Processo Simples</span><h2 class="section-title">Do interesse &agrave; abertura em 5 passos</h2></div>')
[void]$html.AppendLine('<div class="steps-horizontal">')
[void]$html.AppendLine('<div class="step-h"><div class="step-h-number">01</div><div class="step-h-icon">&#128203;</div><h3 class="step-h-title">Preencha o formul&aacute;rio</h3><p class="step-h-text">Nos informe seus dados. Nossa equipe entra em contato em at&eacute; 24h.</p></div><div class="step-h-connector"><div class="step-h-line"></div></div>')
[void]$html.AppendLine('<div class="step-h"><div class="step-h-number">02</div><div class="step-h-icon">&#128202;</div><h3 class="step-h-title">Apresenta&ccedil;&atilde;o</h3><p class="step-h-text">Conhe&ccedil;a o modelo de neg&oacute;cio e o potencial de retorno da sua regi&atilde;o.</p></div><div class="step-h-connector"><div class="step-h-line"></div></div>')
[void]$html.AppendLine('<div class="step-h"><div class="step-h-number">03</div><div class="step-h-icon">&#9989;</div><h3 class="step-h-title">An&aacute;lise</h3><p class="step-h-text">Avaliamos o perfil e a viabilidade do mercado local.</p></div><div class="step-h-connector"><div class="step-h-line"></div></div>')
[void]$html.AppendLine('<div class="step-h"><div class="step-h-number">04</div><div class="step-h-icon">&#9997;</div><h3 class="step-h-title">Contrato</h3><p class="step-h-text">Formalizamos a parceria. Voc&ecirc; &eacute; oficialmente um franqueado Inspirar.</p></div><div class="step-h-connector"><div class="step-h-line"></div></div>')
[void]$html.AppendLine('<div class="step-h"><div class="step-h-number">05</div><div class="step-h-icon">&#128640;</div><h3 class="step-h-title">Abertura</h3><p class="step-h-text">Receba todo o suporte para montar e abrir sua unidade.</p></div>')
[void]$html.AppendLine('</div></div></section>')

# DEPOIMENTOS (3 colunas Kopenhagen style)
[void]$html.AppendLine('<section class="depoimentos" id="depoimentos"><div class="container"><div class="section-header"><span class="section-eyebrow">Depoimentos</span><h2 class="section-title">O que nossos franqueados dizem</h2></div>')
[void]$html.AppendLine('<div class="testimonials-grid">')
[void]$html.AppendLine('<div class="testimonial-card testimonial-featured"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Abri minha unidade em Curitiba h&aacute; 4 anos e desde o primeiro semestre j&aacute; estava recuperando meu investimento. O suporte da Inspirar &eacute; impressionante &mdash; nunca me senti sozinha nessa jornada.</p><div class="testimonial-author"><img src="avatar1.png" alt="Mariana Costa" class="avatar" /><div class="author-info"><strong>Mariana Costa</strong><span>Franqueada &mdash; Curitiba, PR</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('<div class="testimonial-card"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Portf&oacute;lio imenso de cursos na &aacute;rea da sa&uacute;de e uma demanda crescente. Em 22 meses j&aacute; tinha recuperado tudo que investi.</p><div class="testimonial-author"><img src="avatar2.png" alt="Ricardo Almeida" class="avatar" /><div class="author-info"><strong>Ricardo Almeida</strong><span>Franqueado &mdash; Porto Alegre, RS</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('<div class="testimonial-card"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Como profissional da sa&uacute;de, escolhi a Inspirar porque acredito no impacto da educa&ccedil;&atilde;o de qualidade. O retorno superou minhas expectativas.</p><div class="testimonial-author"><img src="avatar3.png" alt="Camila Santos" class="avatar" /><div class="author-info"><strong>Camila Santos</strong><span>Franqueada &mdash; S&atilde;o Paulo, SP</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('</div></div></section>')

# FAQ
[void]$html.AppendLine('<section class="faq" id="faq"><div class="container"><div class="faq-layout"><div class="faq-header-col"><span class="section-eyebrow">FAQ</span><h2 class="section-title">Perguntas frequentes</h2><p class="faq-desc">Tire suas principais d&uacute;vidas sobre o modelo de franquia da Faculdade Inspirar.</p><a href="#contato" class="btn btn-primary" id="btn-faq">Falar com um consultor</a></div><div class="faq-list">')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c1"><span>Qual o investimento inicial para abrir uma franquia?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c1"><p>O investimento varia conforme o modelo escolhido. Para uma unidade presencial, a partir de R$ 390 mil. Para um polo de apoio, a partir de R$ 240 mil. Nossa equipe detalha os valores conforme seu perfil.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c2"><span>Em quanto tempo posso recuperar meu investimento?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c2"><p>O prazo estimado de retorno (ROI) &eacute; de 18 a 24 meses, com base na m&eacute;dia hist&oacute;rica das unidades da rede.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c3"><span>Preciso ter experi&ecirc;ncia no setor de educa&ccedil;&atilde;o?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c3"><p>N&atilde;o &eacute; necess&aacute;rio. A Faculdade Inspirar oferece treinamento inicial completo em todas as &aacute;reas: acad&ecirc;mico, comercial, financeiro e operacional.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c4"><span>Como funciona o suporte da franqueadora?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c4"><p>O suporte &eacute; completo: acad&ecirc;mico, comercial, marketing, jur&iacute;dico, financeiro e consultoria cont&iacute;nua de neg&oacute;cios.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c5"><span>Posso abrir uma unidade em qualquer cidade do Brasil?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c5"><p>Sim! Estamos em expans&atilde;o em todo o Brasil. Analisamos a viabilidade de cada cidade e concedemos territ&oacute;rios exclusivos.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c6"><span>Quais cursos posso oferecer?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c6"><p>Mais de 1.000 cursos nas &aacute;reas de Sa&uacute;de, Bem-estar, Longevidade e Beleza &mdash; p&oacute;s-gradua&ccedil;&atilde;o, MBA, extens&atilde;o e gradua&ccedil;&atilde;o nas modalidades presencial e semipresencial.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item"><button class="accordion-trigger" aria-expanded="false" aria-controls="faq-c7"><span>A Faculdade Inspirar &eacute; credenciada pelo MEC?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-c7"><p>Sim, &eacute; devidamente credenciada e autorizada pelo MEC. Todos os diplomas t&ecirc;m validade nacional.</p></div></div>')
[void]$html.AppendLine('</div></div></div></section>')

# CTA BANNER - fundo azul entre FAQ e formulario (Kopenhagen style)
[void]$html.AppendLine('<section class="cta-banner"><div class="cta-banner-inner"><div class="cta-banner-text"><h2 class="cta-banner-title">Pronto para transformar sua cidade?</h2><p class="cta-banner-sub">Preencha o formul&aacute;rio abaixo e nossa equipe entra em contato em at&eacute; 24 horas.</p></div><a href="#contato" class="btn btn-white btn-lg" id="btn-cta-banner">Quero ser Franqueado &#8594;</a></div></section>')

# CONTATO / FORMULARIO - fundo preto
[void]$html.AppendLine('<section class="contato" id="contato"><div class="contato-bg"></div><div class="container"><div class="contato-layout">')
[void]$html.AppendLine('<div class="contato-info"><span class="section-eyebrow eyebrow-light">D&ecirc; o primeiro passo</span><h2 class="section-title title-light">Pronto para transformar sua cidade?</h2><p class="contato-desc">Preencha o formul&aacute;rio e nossa equipe entrar&aacute; em contato em at&eacute; 24 horas com uma proposta personalizada.</p><div class="contato-features"><div class="contato-feature"><div class="cf-icon">&#9889;</div><div><strong>Resposta em 24h</strong><span>Nossa equipe &eacute; &aacute;gil e comprometida</span></div></div><div class="contato-feature"><div class="cf-icon">&#128274;</div><div><strong>Dados protegidos</strong><span>Suas informa&ccedil;&otilde;es est&atilde;o seguras</span></div></div><div class="contato-feature"><div class="cf-icon">&#127919;</div><div><strong>Proposta personalizada</strong><span>An&aacute;lise para seu mercado</span></div></div></div></div>')
[void]$html.AppendLine('<div class="contato-form-wrapper"><form class="contato-form" id="contato-form" novalidate><h3 class="form-title">Quero ser Franqueado</h3>')
[void]$html.AppendLine('<div class="form-group"><label for="input-nome">Nome completo *</label><input type="text" id="input-nome" name="nome" placeholder="Seu nome completo" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-email">E-mail *</label><input type="email" id="input-email" name="email" placeholder="seu@email.com" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-telefone">Celular *</label><input type="tel" id="input-telefone" name="telefone" placeholder="(00) 00000-0000" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-investimento">Quanto espera investir? *</label><select id="input-investimento" name="investimento" required><option value="">Selecione uma faixa</option><option value="ate-250k">At&eacute; R$ 250 mil</option><option value="250-390k">Entre R$ 250 mil e R$ 390 mil</option><option value="acima-390k">Acima de R$ 390 mil</option><option value="nao-sei">Ainda n&atilde;o sei</option></select></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-cidade">Cidade de interesse *</label><input type="text" id="input-cidade" name="cidade" placeholder="Cidade onde deseja abrir a unidade" required /></div>')
[void]$html.AppendLine('<div class="form-check"><input type="checkbox" id="input-termos" name="termos" required /><label for="input-termos">Concordo com a <a href="https://www.inspirar.com.br/politica-de-privacidade/" target="_blank" rel="noopener noreferrer">Pol&iacute;tica de Privacidade</a> e autorizo o contato comercial.</label></div>')
[void]$html.AppendLine('<button type="submit" class="btn btn-primary btn-full btn-lg" id="btn-submit-form">Enviar meu interesse <span class="btn-arrow">&#8594;</span></button>')
[void]$html.AppendLine('<p class="form-disclaimer">&#128274; Seus dados est&atilde;o protegidos. N&atilde;o fazemos spam.</p>')
[void]$html.AppendLine('</form></div></div></div></section>')

# FOOTER
[void]$html.AppendLine('<footer class="footer"><div class="container"><div class="footer-top"><div class="footer-brand"><div class="footer-logo"><img src="Logo branca - horizontal.png" alt="Faculdade Inspirar" class="footer-logo-img-white" /></div><p class="footer-tagline">Inspirar e encantar faz parte do nosso dia a dia.</p><div class="footer-social"><a href="https://www.inspirar.com.br" class="social-link" target="_blank" title="Site">&#127760;</a><a href="https://wa.me/5508006022828" class="social-link" target="_blank" title="WhatsApp">&#128172;</a></div></div>')
[void]$html.AppendLine('<div class="footer-links"><div class="footer-col"><h4>Institucional</h4><ul><li><a href="https://www.inspirar.com.br/sobre" target="_blank">Sobre a Inspirar</a></li><li><a href="https://www.inspirar.com.br" target="_blank">Unidades</a></li><li><a href="https://www.inspirar.com.br/trabalhe-conosco" target="_blank">Trabalhe Conosco</a></li></ul></div><div class="footer-col"><h4>Cursos</h4><ul><li><a href="https://www.inspirar.com.br" target="_blank">P&oacute;s-Gradua&ccedil;&atilde;o</a></li><li><a href="https://www.inspirar.com.br/home-graduacao/" target="_blank">Gradua&ccedil;&atilde;o</a></li><li><a href="https://www.inspirar.com.br" target="_blank">Extens&atilde;o</a></li></ul></div><div class="footer-col"><h4>Franquia</h4><ul><li><a href="#diferenciais">Diferenciais</a></li><li><a href="#depoimentos">Depoimentos</a></li><li><a href="#contato">Seja Franqueado</a></li></ul></div></div></div>')
[void]$html.AppendLine('<div class="footer-bottom"><p>&copy; 2026 Faculdade Inspirar. Todos os direitos reservados.</p><a href="https://www.inspirar.com.br/politica-de-privacidade/" target="_blank" class="footer-privacy">Pol&iacute;tica de Privacidade</a></div></div></footer>')

# FLOATING CTA + MODAL
[void]$html.AppendLine('<div class="floating-cta" id="floating-cta"><a href="#contato" class="btn btn-primary" id="btn-floating">&#128188; Quero ser Franqueado</a></div>')
[void]$html.AppendLine('<div class="modal-overlay" id="modal-overlay" style="display:none"><div class="modal-box"><div class="modal-icon">&#127881;</div><h3>Interesse registrado!</h3><p>Nossa equipe entrar&aacute; em contato em at&eacute; 24 horas com uma proposta personalizada.</p><button class="btn btn-primary" id="modal-close">Fechar</button></div></div>')
[void]$html.AppendLine('<script src="script.js"></script></body></html>')

[System.IO.File]::WriteAllText("$p\index.html", $html.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "HTML: $([System.IO.File]::ReadAllBytes("$p\index.html").Length) bytes"
