$p = "C:\Users\Usuario\.gemini\antigravity\playground\polar-newton\franquias-inspirar"
$html = [System.Text.StringBuilder]::new()

[void]$html.AppendLine('<!DOCTYPE html>')
[void]$html.AppendLine('<html lang="pt-BR">')
[void]$html.AppendLine('<head>')
[void]$html.AppendLine('<meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />')
[void]$html.AppendLine('<title>Seja um Franqueado | Faculdade Inspirar</title>')
[void]$html.AppendLine('<meta name="description" content="Abra sua unidade da Faculdade Inspirar - maior rede de franquias de pos-graduacao em Saude do Brasil. 29+ anos, 100 mil alunos formados." />')
[void]$html.AppendLine('<link rel="stylesheet" href="styles.css" />')
[void]$html.AppendLine('</head><body>')

# NAVBAR
[void]$html.AppendLine('<nav class="navbar" id="navbar"><div class="nav-container">')
[void]$html.AppendLine('<a href="#hero" class="nav-logo"><img src="Logo branca - horizontal.png" alt="Faculdade Inspirar" class="nav-logo-img" /></a>')
[void]$html.AppendLine('<ul class="nav-links" id="nav-links"><li><a href="#sobre" id="nav-sobre">Sobre</a></li><li><a href="#diferenciais" id="nav-diferenciais">Diferenciais</a></li><li><a href="#investimento" id="nav-investimento">Investimento</a></li><li><a href="#depoimentos" id="nav-depoimentos">Depoimentos</a></li><li><a href="#faq" id="nav-faq">FAQ</a></li></ul>')
[void]$html.AppendLine('<div class="nav-actions"><a href="#contato" class="btn btn-primary btn-nav" id="btn-nav-franqueado">Quero ser Franqueado</a><button class="hamburger" id="hamburger" aria-label="Abrir menu" aria-expanded="false"><span></span><span></span><span></span></button></div>')
[void]$html.AppendLine('</div></nav>')

# HERO
[void]$html.AppendLine('<section class="hero" id="hero"><div class="hero-bg"><img src="hero atualizada.png" alt="Campus Faculdade Inspirar" class="hero-img" /><div class="hero-overlay"></div><div class="hero-gradient"></div></div>')
[void]$html.AppendLine('<div class="hero-content container"><div class="hero-tags"><span class="tag tag-blue" id="tag-premiada">&#11088; Premiada por 8 anos consecutivos</span><span class="tag tag-dark" id="tag-franquias">&#127942; Maior rede de p&oacute;s-gradua&ccedil;&atilde;o em Sa&uacute;de do Brasil</span></div>')
[void]$html.AppendLine('<h1 class="hero-title">Transforme sua cidade com a<br /><span class="gradient-text">Faculdade Inspirar</span></h1>')
[void]$html.AppendLine('<p class="hero-subtitle">Seja parte da maior rede de franquias de educa&ccedil;&atilde;o na &aacute;rea da Sa&uacute;de do Brasil.<br />Mais de 29 anos de tradi&ccedil;&atilde;o, +100 mil alunos formados e presen&ccedil;a em todo o pa&iacute;s.</p>')
[void]$html.AppendLine('<div class="hero-stats"><div class="hero-stat" id="stat-anos"><span class="stat-number">29<span class="stat-plus">+</span></span><span class="stat-label">Anos de mercado</span></div><div class="hero-stat-divider"></div><div class="hero-stat" id="stat-alunos"><span class="stat-number">100K<span class="stat-plus">+</span></span><span class="stat-label">Alunos formados</span></div><div class="hero-stat-divider"></div><div class="hero-stat" id="stat-unidades"><span class="stat-number">40<span class="stat-plus">+</span></span><span class="stat-label">Unidades no Brasil</span></div><div class="hero-stat-divider"></div><div class="hero-stat" id="stat-cursos"><span class="stat-number">1000<span class="stat-plus">+</span></span><span class="stat-label">Cursos dispon&iacute;veis</span></div></div>')
[void]$html.AppendLine('<div class="hero-ctas"><a href="#contato" class="btn btn-primary btn-lg" id="btn-hero-quero">Quero ser Franqueado</a><a href="#sobre" class="btn btn-outline btn-lg" id="btn-hero-saibamais">Saiba mais &#8595;</a></div>')
[void]$html.AppendLine('</div><div class="hero-scroll-indicator" aria-hidden="true"><div class="scroll-dot"></div></div></section>')

# LOGO WALL - apenas 3 selos
[void]$html.AppendLine('<section class="logo-wall" id="logo-wall"><div class="container"><p class="logo-wall-label">Reconhecida pelas maiores organiza&ccedil;&otilde;es do mercado</p><div class="logo-wall-track">')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-serasa"><div class="award-icon">&#127885;</div><span>Serasa Experian</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-pegn"><div class="award-icon">&#128240;</div><span>Peq. Empresas &amp; Grandes Neg.</span></div><div class="logo-wall-divider"></div>')
[void]$html.AppendLine('<div class="logo-wall-item" id="award-mec"><div class="award-icon">&#128203;</div><span>Autorizada pelo MEC</span></div>')
[void]$html.AppendLine('</div></div></section>')

# SOBRE - com foto IMG_7433, sem EAD
[void]$html.AppendLine('<section class="sobre" id="sobre"><div class="container"><div class="sobre-grid"><div class="sobre-content">')
[void]$html.AppendLine('<span class="section-eyebrow">Nossa Hist&oacute;ria</span><h2 class="section-title">A maior e melhor rede de franquias de p&oacute;s-gradua&ccedil;&atilde;o do Brasil</h2>')
[void]$html.AppendLine('<p class="sobre-text">H&aacute; mais de duas d&eacute;cadas no mercado, o Grupo Inspirar est&aacute; presente em todas as regi&otilde;es do pa&iacute;s, al&eacute;m de sedes em Portugal e na Holanda. Destaca-se como institui&ccedil;&atilde;o refer&ecirc;ncia de ensino na &aacute;rea da Sa&uacute;de, com cursos de Gradua&ccedil;&atilde;o, P&oacute;s-gradua&ccedil;&atilde;o, Extens&atilde;o e programas de Mestrado e Doutorado.</p>')
[void]$html.AppendLine('<p class="sobre-text">Reconhecida como a maior e melhor rede de franquias de p&oacute;s-gradua&ccedil;&atilde;o do Brasil segundo a Serasa Experian e a Revista Pequenas Empresas &amp; Grandes Neg&oacute;cios.</p>')
[void]$html.AppendLine('<div class="sobre-badges"><span class="badge" id="badge-saude">&#129658; Refer&ecirc;ncia em Sa&uacute;de</span><span class="badge" id="badge-pos">&#127891; P&oacute;s-Gradua&ccedil;&atilde;o</span><span class="badge" id="badge-extensao">&#128218; Extens&atilde;o</span><span class="badge" id="badge-mestrado">&#128300; Mestrado e Doutorado</span></div>')
[void]$html.AppendLine('</div><div class="sobre-visual"><div class="sobre-img-wrapper"><img src="IMG_7433.JPG" alt="Faculdade Inspirar" class="sobre-img" /><div class="sobre-img-card" id="sobre-card-retorno"><div class="img-card-icon">&#128176;</div><div class="img-card-content"><strong>Retorno em 18&ndash;24 meses</strong><span>Prazo estimado de ROI</span></div></div></div></div>')
[void]$html.AppendLine('</div></div></section>')

# BENTO / DIFERENCIAIS - sem EAD, bento-dark corrigido, sem ilustracao esquisita, sem nutricao
[void]$html.AppendLine('<section class="diferenciais" id="diferenciais"><div class="container">')
[void]$html.AppendLine('<div class="section-header"><span class="section-eyebrow">Por que escolher a Inspirar?</span><h2 class="section-title">Diferenciais que fazem a diferen&ccedil;a</h2><p class="section-subtitle">Tudo que voc&ecirc; precisa para construir um neg&oacute;cio s&oacute;lido e lucrativo.</p></div>')
[void]$html.AppendLine('<div class="bento-grid">')
[void]$html.AppendLine('<div class="bento-card bento-large" id="bento-marca"><div class="bento-icon">&#127942;</div><h3>Marca Premium &amp; Consolidada</h3><p>29+ anos de hist&oacute;ria e autoridade reconhecida no mercado de sa&uacute;de. Uma marca que abre portas e gera confian&ccedil;a instant&acirc;nea.</p></div>')
[void]$html.AppendLine('<div class="bento-card bento-tall" id="bento-suporte"><div class="bento-icon">&#129309;</div><h3>Suporte Completo</h3><p>Apoio comercial, acad&ecirc;mico, jur&iacute;dico e de marketing. Voc&ecirc; nunca estar&aacute; sozinho.</p><ul class="bento-list"><li>&#10003; Treinamento inicial completo</li><li>&#10003; Suporte acad&ecirc;mico 24/7</li><li>&#10003; Materiais de marketing</li><li>&#10003; Consultoria de neg&oacute;cios</li></ul></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium" id="bento-cursos"><div class="bento-icon">&#128218;</div><h3>+1.000 Cursos</h3><p>Portf&oacute;lio vasto cobrindo toda a cadeia de sa&uacute;de, bem-estar, est&eacute;tica e longevidade.</p><div class="bento-tags"><span class="mini-tag">Fisioterapia</span><span class="mini-tag">Est&eacute;tica</span><span class="mini-tag">Psicologia</span><span class="mini-tag">Enfermagem</span><span class="mini-tag">Osteopatia</span><span class="mini-tag">+ muito mais</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium bento-blue" id="bento-retorno"><div class="bento-icon">&#128200;</div><h3>Retorno R&aacute;pido</h3><p>Previs&atilde;o de retorno do investimento entre 18 e 24 meses com modelo validado.</p><div class="bento-metric"><span class="metric-number">18&ndash;24</span><span class="metric-label">meses para ROI</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-wide" id="bento-presenca"><div class="bento-icon">&#127758;</div><h3>Presen&ccedil;a Nacional e Internacional</h3><p>Mais de 40 unidades em todas as regi&otilde;es do Brasil, Portugal e Holanda.</p><div class="bento-cities"><span>S&atilde;o Paulo</span><span>Rio de Janeiro</span><span>Curitiba</span><span>Porto Alegre</span><span>Bras&iacute;lia</span><span>Salvador</span><span>Fortaleza</span><span>Belo Horizonte</span><span>+32 cidades</span></div></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium bento-premiada-card" id="bento-premiada"><div class="bento-icon">&#11088;</div><h3>Premiada 8x</h3><p>8 anos consecutivos entre as 5 melhores franquias de cursos do Brasil.</p></div>')
[void]$html.AppendLine('<div class="bento-card bento-medium" id="bento-territorio"><div class="bento-icon">&#127968;</div><h3>Exclusividade Territorial</h3><p>Cada franqueado recebe exclusividade na sua cidade, garantindo protec&atilde;o de mercado e crescimento sustent&aacute;vel.</p></div>')
[void]$html.AppendLine('</div></div></section>')

# PLANS - sem o titulo "Escolha o modelo ideal"
[void]$html.AppendLine('<section class="investimento" id="investimento"><div class="container">')
[void]$html.AppendLine('<div class="section-header"><span class="section-eyebrow">Modelos de Franquia</span><h2 class="section-title">Invista em educa&ccedil;&atilde;o com uma marca l&iacute;der</h2><p class="section-subtitle">Op&ccedil;&otilde;es flex&iacute;veis para diferentes perfis de empreendedores.</p></div>')
[void]$html.AppendLine('<div class="plans-grid">')
[void]$html.AppendLine('<div class="plan-card" id="plan-polo"><div class="plan-badge">Mais Acess&iacute;vel</div><div class="plan-icon">&#127919;</div><h3 class="plan-name">Polo de Apoio Presencial</h3><p class="plan-desc">Unidade de apoio aos alunos com estrutura enxuta e alto potencial de retorno.</p><div class="plan-invest"><span class="invest-from">A partir de</span><div class="invest-value">R$ 240<span class="invest-k">mil</span></div></div><ul class="plan-features"><li><span class="check-icon">&#10003;</span> Portf&oacute;lio completo de cursos</li><li><span class="check-icon">&#10003;</span> Suporte acad&ecirc;mico</li><li><span class="check-icon">&#10003;</span> Material de marketing</li><li><span class="check-icon">&#10003;</span> Treinamento inicial</li><li><span class="check-icon">&#10003;</span> Exclusividade territorial</li></ul><a href="#contato" class="btn btn-outline btn-full" id="btn-plan-polo">Quero este modelo</a></div>')
[void]$html.AppendLine('<div class="plan-card plan-featured" id="plan-unidade"><div class="plan-badge plan-badge-featured">&#11088; Mais Popular</div><div class="plan-icon">&#127963;</div><h3 class="plan-name">Unidade Presencial</h3><p class="plan-desc">Unidade f&iacute;sica completa com cursos presenciais e semipresenciais.</p><div class="plan-invest"><span class="invest-from">A partir de</span><div class="invest-value">R$ 390<span class="invest-k">mil</span></div></div><ul class="plan-features"><li><span class="check-icon">&#10003;</span> Espa&ccedil;o f&iacute;sico equipado</li><li><span class="check-icon">&#10003;</span> Cursos presenciais + semipresencial</li><li><span class="check-icon">&#10003;</span> Suporte completo 360&deg;</li><li><span class="check-icon">&#10003;</span> Exclusividade territorial</li><li><span class="check-icon">&#10003;</span> Consultoria de expans&atilde;o</li><li><span class="check-icon">&#10003;</span> Acesso ao portf&oacute;lio premium</li></ul><a href="#contato" class="btn btn-primary btn-full" id="btn-plan-unidade">Quero este modelo</a></div>')
[void]$html.AppendLine('<div class="plan-card" id="plan-semipresencial"><div class="plan-badge">Flex&iacute;vel</div><div class="plan-icon">&#128260;</div><h3 class="plan-name">Semipresencial</h3><p class="plan-desc">O melhor dos dois mundos: combine aulas presenciais com conte&uacute;do online.</p><div class="plan-invest"><span class="invest-from">Consulte</span><div class="invest-value" style="font-size:1.8rem;line-height:1.2">Condi&ccedil;&otilde;es especiais</div></div><ul class="plan-features"><li><span class="check-icon">&#10003;</span> Modelo h&iacute;brido</li><li><span class="check-icon">&#10003;</span> Maior flexibilidade</li><li><span class="check-icon">&#10003;</span> Suporte acad&ecirc;mico</li><li><span class="check-icon">&#10003;</span> Portf&oacute;lio diversificado</li><li><span class="check-icon">&#10003;</span> Gest&atilde;o simplificada</li></ul><a href="#contato" class="btn btn-outline btn-full" id="btn-plan-semi">Quero este modelo</a></div>')
[void]$html.AppendLine('</div></div></section>')

# HOW IT WORKS
[void]$html.AppendLine('<section class="como-funciona" id="como-funciona"><div class="container">')
[void]$html.AppendLine('<div class="section-header section-header-light"><span class="section-eyebrow eyebrow-light">Processo Simples</span><h2 class="section-title title-light">Do interesse &agrave; abertura em poucos passos</h2></div>')
[void]$html.AppendLine('<div class="steps-list">')
[void]$html.AppendLine('<div class="step-item" id="step-1"><div class="step-number">01</div><div class="step-content"><h3>Preencha o formul&aacute;rio de interesse</h3><p>Nos informe seus dados e a cidade onde deseja abrir. Nossa equipe entra em contato em at&eacute; 24h.</p></div><div class="step-icon">&#128203;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-2"><div class="step-number">02</div><div class="step-content"><h3>Apresenta&ccedil;&atilde;o do modelo de neg&oacute;cio</h3><p>Conhe&ccedil;a em detalhes como funciona a franquia, os n&uacute;meros e o potencial de retorno da sua regi&atilde;o.</p></div><div class="step-icon">&#128202;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-3"><div class="step-number">03</div><div class="step-content"><h3>An&aacute;lise e aprova&ccedil;&atilde;o</h3><p>Nossa equipe avalia o perfil e a viabilidade do mercado local para garantir o sucesso da unidade.</p></div><div class="step-icon">&#9989;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-4"><div class="step-number">04</div><div class="step-content"><h3>Assinatura do contrato</h3><p>Formalizamos a parceria e voc&ecirc; passa a fazer parte da rede Inspirar oficialmente.</p></div><div class="step-icon">&#9997;</div></div><div class="step-connector"></div>')
[void]$html.AppendLine('<div class="step-item" id="step-5"><div class="step-number">05</div><div class="step-content"><h3>Treinamento e abertura</h3><p>Voc&ecirc; recebe todo o suporte para montar sua unidade e acompanhamento nos primeiros meses.</p></div><div class="step-icon">&#128640;</div></div>')
[void]$html.AppendLine('</div></div></section>')

# TESTIMONIALS
[void]$html.AppendLine('<section class="depoimentos" id="depoimentos"><div class="container">')
[void]$html.AppendLine('<div class="section-header"><span class="section-eyebrow">Depoimentos</span><h2 class="section-title">O que nossos franqueados dizem</h2><p class="section-subtitle">Hist&oacute;rias reais de quem escolheu investir no futuro com a Faculdade Inspirar.</p></div>')
[void]$html.AppendLine('<div class="testimonials-grid">')
[void]$html.AppendLine('<div class="testimonial-card testimonial-featured" id="testimonial-1"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Abri minha unidade em Curitiba h&aacute; 4 anos e desde o primeiro semestre j&aacute; estava recuperando meu investimento. O suporte da Inspirar &eacute; impressionante &mdash; nunca me senti sozinha nessa jornada. A marca j&aacute; vem com credibilidade, o que facilita muito a capta&ccedil;&atilde;o de alunos.</p><div class="testimonial-author"><img src="avatar1.png" alt="Mariana Costa" class="avatar" /><div class="author-info"><strong id="testimonial-author-1">Mariana Costa</strong><span>Franqueada &mdash; Curitiba, PR</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('<div class="testimonial-card" id="testimonial-2"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Estava buscando um neg&oacute;cio s&oacute;lido na &aacute;rea da educa&ccedil;&atilde;o e a Inspirar foi a escolha certa. Portf&oacute;lio imenso de cursos na &aacute;rea da sa&uacute;de e uma demanda crescente. Em 22 meses j&aacute; tinha recuperado tudo que investi.</p><div class="testimonial-author"><img src="avatar2.png" alt="Ricardo Almeida" class="avatar" /><div class="author-info"><strong id="testimonial-author-2">Ricardo Almeida</strong><span>Franqueado &mdash; Porto Alegre, RS</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('<div class="testimonial-card" id="testimonial-3"><div class="testimonial-quote">&ldquo;</div><p class="testimonial-text">Como profissional da sa&uacute;de, escolhi a Inspirar porque acredito no impacto da educa&ccedil;&atilde;o de qualidade. O modelo de franquia &eacute; muito bem estruturado e o retorno superou minhas expectativas.</p><div class="testimonial-author"><img src="avatar3.png" alt="Camila Santos" class="avatar" /><div class="author-info"><strong id="testimonial-author-3">Camila Santos</strong><span>Franqueada &mdash; S&atilde;o Paulo, SP</span><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div></div></div></div>')
[void]$html.AppendLine('</div></div></section>')

# FAQ
[void]$html.AppendLine('<section class="faq" id="faq"><div class="container"><div class="faq-layout">')
[void]$html.AppendLine('<div class="faq-header-col"><span class="section-eyebrow">FAQ</span><h2 class="section-title">Perguntas frequentes</h2><p class="faq-desc">Tire suas principais d&uacute;vidas sobre o modelo de franquia da Faculdade Inspirar.</p><a href="#contato" class="btn btn-primary" id="btn-faq-contato">Falar com um consultor</a></div>')
[void]$html.AppendLine('<div class="faq-list" id="faq-list">')
[void]$html.AppendLine('<div class="accordion-item" id="faq-1"><button class="accordion-trigger" id="faq-trigger-1" aria-expanded="false" aria-controls="faq-content-1"><span>Qual o investimento inicial para abrir uma franquia?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-1"><p>O investimento varia conforme o modelo. Para um polo de apoio presencial come&ccedil;a a partir de R$ 240 mil. Para uma unidade presencial completa, chega a R$ 390 mil. Nossa equipe pode detalhar os valores com base no seu perfil e cidade.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-2"><button class="accordion-trigger" id="faq-trigger-2" aria-expanded="false" aria-controls="faq-content-2"><span>Em quanto tempo posso recuperar meu investimento?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-2"><p>O prazo estimado de retorno (ROI) &eacute; de 18 a 24 meses, dependendo do modelo e da performance da unidade. Esse prazo &eacute; baseado na m&eacute;dia hist&oacute;rica das unidades da rede.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-3"><button class="accordion-trigger" id="faq-trigger-3" aria-expanded="false" aria-controls="faq-content-3"><span>Preciso ter experi&ecirc;ncia no setor de educa&ccedil;&atilde;o?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-3"><p>N&atilde;o &eacute; necess&aacute;rio. A Faculdade Inspirar oferece treinamento inicial completo cobrindo todas as &aacute;reas: acad&ecirc;mico, comercial, financeiro e operacional.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-4"><button class="accordion-trigger" id="faq-trigger-4" aria-expanded="false" aria-controls="faq-content-4"><span>Como funciona o suporte da franqueadora?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-4"><p>O suporte &eacute; completo e multidisciplinar: acad&ecirc;mico, comercial, marketing com materiais e campanhas nacionais, jur&iacute;dico, financeiro e consultoria cont&iacute;nua de neg&oacute;cios.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-5"><button class="accordion-trigger" id="faq-trigger-5" aria-expanded="false" aria-controls="faq-content-5"><span>Posso abrir uma unidade em qualquer cidade do Brasil?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-5"><p>Sim! A Faculdade Inspirar est&aacute; em expans&atilde;o em todo o Brasil. Analisamos a viabilidade de mercado de cada cidade e concedemos territ&oacute;rios exclusivos.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-6"><button class="accordion-trigger" id="faq-trigger-6" aria-expanded="false" aria-controls="faq-content-6"><span>Quais cursos posso oferecer na minha unidade?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-6"><p>Mais de 1.000 cursos nas &aacute;reas de Sa&uacute;de, Bem-estar, Longevidade e Beleza, incluindo p&oacute;s-gradua&ccedil;&atilde;o, MBA, extens&atilde;o, gradua&ccedil;&atilde;o e forma&ccedil;&atilde;o. Nas modalidades presencial e semipresencial.</p></div></div>')
[void]$html.AppendLine('<div class="accordion-item" id="faq-7"><button class="accordion-trigger" id="faq-trigger-7" aria-expanded="false" aria-controls="faq-content-7"><span>A Faculdade Inspirar &eacute; credenciada pelo MEC?</span><span class="accordion-icon">+</span></button><div class="accordion-content" id="faq-content-7"><p>Sim, a Faculdade Inspirar &eacute; devidamente credenciada e autorizada pelo MEC. Todos os diplomas t&ecirc;m validade nacional.</p></div></div>')
[void]$html.AppendLine('</div></div></div></section>')

# CONTACT - sem whatsapp, formulario simplificado
[void]$html.AppendLine('<section class="contato" id="contato"><div class="contato-bg"></div><div class="container"><div class="contato-layout">')
[void]$html.AppendLine('<div class="contato-info"><span class="section-eyebrow eyebrow-light">D&ecirc; o primeiro passo</span><h2 class="section-title title-light">Pronto para transformar sua cidade?</h2><p class="contato-desc">Preencha o formul&aacute;rio e nossa equipe entrar&aacute; em contato em at&eacute; 24 horas com uma proposta personalizada.</p>')
[void]$html.AppendLine('<div class="contato-features"><div class="contato-feature" id="cf-1"><div class="cf-icon">&#9889;</div><div><strong>Resposta em 24h</strong><span>Nossa equipe &eacute; &aacute;gil e comprometida</span></div></div><div class="contato-feature" id="cf-2"><div class="cf-icon">&#128274;</div><div><strong>Dados protegidos</strong><span>Suas informa&ccedil;&otilde;es est&atilde;o seguras</span></div></div><div class="contato-feature" id="cf-3"><div class="cf-icon">&#127919;</div><div><strong>Proposta personalizada</strong><span>An&aacute;lise para seu mercado</span></div></div></div>')
[void]$html.AppendLine('</div>')
[void]$html.AppendLine('<div class="contato-form-wrapper"><form class="contato-form" id="contato-form" novalidate><h3 class="form-title">Quero ser Franqueado</h3>')
[void]$html.AppendLine('<div class="form-group"><label for="input-nome">Nome completo *</label><input type="text" id="input-nome" name="nome" placeholder="Seu nome completo" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-email">E-mail *</label><input type="email" id="input-email" name="email" placeholder="seu@email.com" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-telefone">Celular *</label><input type="tel" id="input-telefone" name="telefone" placeholder="(00) 00000-0000" required /></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-investimento">Quanto espera investir? *</label><select id="input-investimento" name="investimento" required><option value="">Selecione uma faixa</option><option value="ate-250k">At&eacute; R$ 250 mil</option><option value="250-390k">Entre R$ 250 mil e R$ 390 mil</option><option value="acima-390k">Acima de R$ 390 mil</option><option value="nao-sei">Ainda n&atilde;o sei</option></select></div>')
[void]$html.AppendLine('<div class="form-group"><label for="input-cidade">Cidade de interesse *</label><input type="text" id="input-cidade" name="cidade" placeholder="Cidade onde deseja abrir a unidade" required /></div>')
[void]$html.AppendLine('<div class="form-check"><input type="checkbox" id="input-termos" name="termos" required /><label for="input-termos">Concordo com a <a href="https://www.inspirar.com.br/politica-de-privacidade/" target="_blank" rel="noopener noreferrer">Pol&iacute;tica de Privacidade</a> e autorizo o contato comercial.</label></div>')
[void]$html.AppendLine('<button type="submit" class="btn btn-primary btn-full btn-lg" id="btn-submit-form">Enviar meu interesse <span class="btn-arrow">&#8594;</span></button>')
[void]$html.AppendLine('<p class="form-disclaimer">&#128274; Seus dados est&atilde;o protegidos. N&atilde;o fazemos spam.</p>')
[void]$html.AppendLine('</form></div></div></div></section>')

# FOOTER
[void]$html.AppendLine('<footer class="footer"><div class="container"><div class="footer-top">')
[void]$html.AppendLine('<div class="footer-brand"><div class="footer-logo"><img src="Logo branca - horizontal.png" alt="Faculdade Inspirar" class="footer-logo-img-white" /></div><p class="footer-tagline">Inspirar e encantar faz parte do nosso dia a dia.</p><div class="footer-social"><a href="https://www.inspirar.com.br" class="social-link" id="social-site" target="_blank" rel="noopener noreferrer" title="Site">&#127760;</a><a href="https://wa.me/5508006022828" class="social-link" id="social-whatsapp" target="_blank" rel="noopener noreferrer" title="WhatsApp">&#128172;</a></div></div>')
[void]$html.AppendLine('<div class="footer-links"><div class="footer-col"><h4>Institucional</h4><ul><li><a href="https://www.inspirar.com.br/sobre" target="_blank">Sobre a Inspirar</a></li><li><a href="https://www.inspirar.com.br" target="_blank">Unidades</a></li><li><a href="https://www.inspirar.com.br/trabalhe-conosco" target="_blank">Trabalhe Conosco</a></li><li><a href="https://www.inspirar.com.br/ouvidoria" target="_blank">Ouvidoria</a></li></ul></div><div class="footer-col"><h4>Cursos</h4><ul><li><a href="https://www.inspirar.com.br" target="_blank">P&oacute;s-Gradua&ccedil;&atilde;o</a></li><li><a href="https://www.inspirar.com.br/home-graduacao/" target="_blank">Gradua&ccedil;&atilde;o</a></li><li><a href="https://www.inspirar.com.br" target="_blank">Extens&atilde;o</a></li></ul></div><div class="footer-col"><h4>Franquia</h4><ul><li><a href="#diferenciais">Diferenciais</a></li><li><a href="#investimento">Modelos</a></li><li><a href="#depoimentos">Depoimentos</a></li><li><a href="#contato">Seja Franqueado</a></li></ul></div></div>')
[void]$html.AppendLine('</div><div class="footer-bottom"><p>&copy; 2026 Faculdade Inspirar. Todos os direitos reservados.</p><a href="https://www.inspirar.com.br/politica-de-privacidade/" target="_blank" rel="noopener noreferrer" class="footer-privacy">Pol&iacute;tica de Privacidade</a></div></div></footer>')

# FLOATING + MODAL + SCRIPT
[void]$html.AppendLine('<div class="floating-cta" id="floating-cta"><a href="#contato" class="btn btn-primary" id="btn-floating">&#128188; Quero ser Franqueado</a></div>')
[void]$html.AppendLine('<div class="modal-overlay" id="modal-overlay" style="display:none"><div class="modal-box"><div class="modal-icon">&#127881;</div><h3 id="modal-title">Interesse registrado!</h3><p>Nossa equipe entrar&aacute; em contato em at&eacute; 24 horas com uma proposta personalizada.</p><button class="btn btn-primary" id="modal-close">Fechar</button></div></div>')
[void]$html.AppendLine('<script src="script.js"></script></body></html>')

[System.IO.File]::WriteAllText("$p\index.html", $html.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "HTML written: $([System.IO.File]::ReadAllBytes("$p\index.html").Length) bytes"
